declare module 'prismjs/components/prism-javascript' {}
declare module 'prismjs/components/prism-typescript' {}
declare module 'prismjs/components/prism-python' {}
declare module 'prismjs/components/prism-java' {}
declare module 'prismjs/components/prism-sql' {}
declare module 'prismjs/components/prism-bash' {}
declare module 'prismjs/components/prism-json' {}
declare module 'prismjs/components/prism-yaml' {}
declare module 'prismjs/components/prism-xml-doc' {}
declare module 'prismjs/components/prism-css' {}
declare module 'prismjs/components/prism-markup' {}
declare module 'prismjs/components/prism-markdown' {}
declare module 'prismjs/components/prism-php' {}
declare module 'prismjs/components/prism-ruby' {}
declare module 'prismjs/components/prism-go' {}
declare module 'prismjs/components/prism-rust' {}
declare module 'prismjs/components/prism-swift' {}
declare module 'prismjs/components/prism-kotlin' {}
declare module 'prismjs/components/prism-dart' {}
declare module 'prismjs/components/prism-c' {}
declare module 'prismjs/components/prism-cpp' {}
declare module 'prismjs/components/prism-csharp' {} 